--CREATE DATABASE CONSOLR;

CREATE TABLE CONSOLR_LOGIN_INFO(
    UID INT NOT NULL AUTO_INCREMENT,
    TUMBLR_NAME VARCHAR(255) NOT NULL,
    LAST_LOGIN TIMESTAMP NOT NULL,

    PRIMARY KEY (uid)
) ENGINE=INNODB;

CREATE TABLE CONSOLR_SETTINGS(
    KEY_SEQ INT NOT NULL AUTO_INCREMENT,
    UID VARCHAR(512) NOT NULL,
    SETTING_KEY VARCHAR(255) NOT NULL,
    SETTING_VALUE VARCHAR(1024),
    
    PRIMARY KEY (KEY_SEQ)

) ENGINE=INNODB;
